
{{/* debug */}}
{{/*- if eq .Values.name "fonttools" }}
{{- include "community.dump" ( printf "debug:\n%s\nend debug" ( ( include "community.build" . ) | toYaml ) ) }}
{{- end */}}
{{/* end debug */}}

{{ template "community.build" . }}
