@startuml

entity "loopup" as utils/loopup << (u,#4B0082) >> {

}
entity "cascadia-code" as fonts/cascadia-code << (f,#48D1CC) >> {

}
entity "fontawesome" as fonts/fontawesome << (f,#48D1CC) >> {

}
entity "font-cursor-misc" as fonts/font-cursor-misc << (f,#48D1CC) >> {

}
entity "inconsolata" as fonts/inconsolata << (f,#48D1CC) >> {

}
entity "inconsolata-hellenic" as fonts/inconsolata-hellenic << (f,#48D1CC) >> {

}
entity "jetbrains-mono" as fonts/jetbrains-mono << (f,#48D1CC) >> {

}
entity "lato" as fonts/lato << (f,#48D1CC) >> {

}
entity "noto-cjk" as fonts/noto-cjk << (f,#48D1CC) >> {

}
entity "noto-extra" as fonts/noto-extra << (f,#48D1CC) >> {

}
entity "roboto" as fonts/roboto << (f,#48D1CC) >> {

}
entity "robotomono" as fonts/robotomono << (f,#48D1CC) >> {

}
entity "robotoslab" as fonts/robotoslab << (f,#48D1CC) >> {

}
entity "stix-fonts" as fonts/stix-fonts << (f,#48D1CC) >> {

}
entity "texcm-ttf" as fonts/texcm-ttf << (f,#48D1CC) >> {

}
entity "wqy-zenhei" as fonts/wqy-zenhei << (f,#48D1CC) >> {

}
entity "wqy-microhei" as fonts/wqy-microhei << (f,#48D1CC) >> {

}
entity "fluid-soundfont" as fonts/fluid-soundfont << (f,#48D1CC) >> {

}
entity "analitza" as libs/analitza << (l,#FF7700) >> {

}
entity "AOMediaCodecs" as libs/AOMediaCodecs << (l,#FF7700) >> {

}
entity "aubio" as libs/aubio << (l,#FF7700) >> {

}
entity "babl-gegl" as libs/babl-gegl << (l,#FF7700) >> {

}
entity "beautifulsoup4" as libs/beautifulsoup4 << (l,#FF7700) >> {

}
entity "breeze-plymouth" as libs/breeze-plymouth << (l,#FF7700) >> {

}
entity "cfitsio" as libs/cfitsio << (l,#FF7700) >> {

}
entity "chrome-binary-plugins" as libs/chrome-binary-plugins << (l,#FF7700) >> {

}
entity "colorama" as libs/colorama << (l,#FF7700) >> {

}
entity "cpp-httplib" as libs/cpp-httplib << (l,#FF7700) >> {

}
entity "css-parser" as libs/css-parser << (l,#FF7700) >> {

}
entity "cssselect" as libs/cssselect << (l,#FF7700) >> {

}
entity "feedparser" as libs/feedparser << (l,#FF7700) >> {

}
entity "fltk" as libs/fltk << (l,#FF7700) >> {

}
entity "freeimage" as libs/freeimage << (l,#FF7700) >> {

}
entity "freeradius-client" as apps/freeradius-client << (a,#FF00FF) >> {

}
entity "ftgl" as libs/ftgl << (l,#FF7700) >> {

}
entity "game-music-emu" as libs/game-music-emu << (l,#FF7700) >> {

}
entity "gl2ps" as libs/gl2ps << (l,#FF7700) >> {

}
entity "glfw" as libs/glfw << (l,#FF7700) >> {

}
entity "goocanvas" as libs/goocanvas << (l,#FF7700) >> {

}
entity "gpm" as libs/gpm << (l,#FF7700) >> {

}
entity "gst-plugins-srtp" as libs/gst-plugins-srtp << (l,#FF7700) >> {

}
entity "gst-plugins-v4l2" as libs/gst-plugins-v4l2 << (l,#FF7700) >> {

}
entity "gtksourceviewmm" as libs/gtksourceviewmm << (l,#FF7700) >> {

}
entity "gupnp-igd" as libs/gupnp-igd << (l,#FF7700) >> {

}
entity "hidapi" as libs/hidapi << (l,#FF7700) >> {

}
entity "id3lib" as libs/id3lib << (l,#FF7700) >> {

}
entity "iniparser" as libs/iniparser << (l,#FF7700) >> {

}
entity "intel-mediasdk" as libs/intel-mediasdk << (l,#FF7700) >> {

}
entity "IO-Tty" as libs/IO-Tty << (l,#FF7700) >> {

}
entity "jbigkit" as libs/jbigkit << (l,#FF7700) >> {

}
entity "ladspa-sdk" as libs/ladspa-sdk << (l,#FF7700) >> {

}
entity "leptonica" as libs/leptonica << (l,#FF7700) >> {

}
entity "lib3ds" as libs/lib3ds << (l,#FF7700) >> {

}
entity "libbs2b" as libs/libbs2b << (l,#FF7700) >> {

}
entity "libcerf" as libs/libcerf << (l,#FF7700) >> {

}
entity "libchamplain" as libs/libchamplain << (l,#FF7700) >> {

}
entity "libconfig" as libs/libconfig << (l,#FF7700) >> {

}
entity "libdiscid" as libs/libdiscid << (l,#FF7700) >> {

}
entity "libdispatch" as libs/libdispatch << (l,#FF7700) >> {

}
entity "libebur128" as libs/libebur128 << (l,#FF7700) >> {

}
entity "libemf" as libs/libemf << (l,#FF7700) >> {

}
entity "libgii" as libs/libgii << (l,#FF7700) >> {

}
entity "libglade" as libs/libglade << (l,#FF7700) >> {

}
entity "libharu" as libs/libharu << (l,#FF7700) >> {

}
entity "libktorrent" as libs/libktorrent << (l,#FF7700) >> {

}
entity "liblo" as libs/liblo << (l,#FF7700) >> {

}
entity "liblqr" as libs/liblqr << (l,#FF7700) >> {

}
entity "libmirage" as libs/libmirage << (l,#FF7700) >> {

}
entity "libmp4v2" as libs/libmp4v2 << (l,#FF7700) >> {

}
entity "libopusenc" as libs/libopusenc << (l,#FF7700) >> {

}
entity "libprojectm" as libs/libprojectm << (l,#FF7700) >> {

}
entity "libsfml" as libs/libsfml << (l,#FF7700) >> {

}
entity "libshout" as libs/libshout << (l,#FF7700) >> {

}
entity "libsidplay" as libs/libsidplay << (l,#FF7700) >> {

}
entity "libsidplayfp" as libs/libsidplayfp << (l,#FF7700) >> {

}
entity "libsoundtouch" as libs/libsoundtouch << (l,#FF7700) >> {

}
entity "libutf8proc" as libs/libutf8proc << (l,#FF7700) >> {

}
entity "libvisio" as libs/libvisio << (l,#FF7700) >> {

}
entity "libXaw3d" as libs/libXaw3d << (l,#FF7700) >> {

}
entity "lrzsz" as libs/lrzsz << (l,#FF7700) >> {

}
entity "lttng-ust-2_12" as libs/lttng-ust-2_12 << (l,#FF7700) >> {

}
entity "LuaBitOp" as libs/LuaBitOp << (l,#FF7700) >> {

}
entity "lv2" as libs/lv2 << (l,#FF7700) >> {

}
entity "lzip" as libs/lzip << (l,#FF7700) >> {

}
entity "mac" as libs/mac << (l,#FF7700) >> {

}
entity "mathjax" as libs/mathjax << (l,#FF7700) >> {

}
entity "mbedtls" as libs/mbedtls << (l,#FF7700) >> {

}
entity "motif" as libs/motif << (l,#FF7700) >> {

}
entity "mxml" as libs/mxml << (l,#FF7700) >> {

}
entity "nas" as libs/nas << (l,#FF7700) >> {

}
entity "neXtaw" as libs/neXtaw << (l,#FF7700) >> {

}
entity "nlohmann_json" as libs/nlohmann_json << (l,#FF7700) >> {

}
entity "oniguruma" as libs/oniguruma << (l,#FF7700) >> {

}
entity "ossp-uuid" as libs/ossp-uuid << (l,#FF7700) >> {

}
entity "physfs" as libs/physfs << (l,#FF7700) >> {

}
entity "portsmf" as libs/portsmf << (l,#FF7700) >> {

}
entity "pyproject-hooks" as libs/pyproject-hooks << (l,#FF7700) >> {

}
entity "python-msgpack" as libs/python-msgpack << (l,#FF7700) >> {

}
entity "python-protobuf" as libs/python-protobuf << (l,#FF7700) >> {

}
entity "qcustomplot" as libs/qcustomplot << (l,#FF7700) >> {

}
entity "qscintilla" as libs/qscintilla << (l,#FF7700) >> {

}
entity "qscintilla-qt5" as libs/qscintilla-qt5 << (l,#FF7700) >> {

}
entity "qtpy" as libs/qtpy << (l,#FF7700) >> {

}
entity "qxlsx" as libs/qxlsx << (l,#FF7700) >> {

}
entity "rapidjson" as libs/rapidjson << (l,#FF7700) >> {

}
entity "regex" as libs/regex << (l,#FF7700) >> {

}
entity "reportlab" as libs/reportlab << (l,#FF7700) >> {

}
entity "rnnoise" as apps/rnnoise << (a,#FF00FF) >> {

}
entity "rtaudio" as libs/rtaudio << (l,#FF7700) >> {

}
entity "rtmidi" as libs/rtmidi << (l,#FF7700) >> {

}
entity "send2trash" as libs/send2trash << (l,#FF7700) >> {

}
entity "sgml-common" as libs/sgml-common << (l,#FF7700) >> {

}
entity "smpeg" as libs/smpeg << (l,#FF7700) >> {

}
entity "smpeg2" as libs/smpeg2 << (l,#FF7700) >> {

}
entity "tbb" as libs/tbb << (l,#FF7700) >> {

}
entity "tinyxml2" as libs/tinyxml2 << (l,#FF7700) >> {

}
entity "tree-sitter" as libs/tree-sitter << (l,#FF7700) >> {

}
entity "twisted" as libs/twisted << (l,#FF7700) >> {

}
entity "uthash" as libs/uthash << (l,#FF7700) >> {

}
entity "utfcpp" as libs/utfcpp << (l,#FF7700) >> {

}
entity "vamp-plugin-sdk" as libs/vamp-plugin-sdk << (l,#FF7700) >> {

}
entity "websocketpp" as libs/websocketpp << (l,#FF7700) >> {

}
entity "python-deprecated" as libs/python-deprecated << (l,#FF7700) >> {

}
entity "vdf" as libs/vdf << (l,#FF7700) >> {

}
entity "wxGTK" as libs/wxGTK << (l,#FF7700) >> {

}
entity "wxGTK-3_0-gtk3" as libs/wxGTK-3_0-gtk3 << (l,#FF7700) >> {

}
entity "xsimd" as libs/xsimd << (l,#FF7700) >> {

}
entity "zimg" as libs/zimg << (l,#FF7700) >> {

}
entity "zita-convolver" as libs/zita-convolver << (l,#FF7700) >> {

}
entity "alacritty" as apps/alacritty << (a,#FF00FF) >> {

}
entity "alligator" as apps/alligator << (a,#FF00FF) >> {

}
entity "amarok" as apps/amarok << (a,#FF00FF) >> {

}
entity "amberol" as apps/amberol << (a,#FF00FF) >> {

}
entity "android-tools" as apps/android-tools << (a,#FF00FF) >> {

}
entity "ant" as apps/ant << (a,#FF00FF) >> {

}
entity "astyle" as apps/astyle << (a,#FF00FF) >> {

}
entity "apcupsd" as apps/apcupsd << (a,#FF00FF) >> {

}
entity "argouml" as apps/argouml << (a,#FF00FF) >> {

}
entity "argyllcms" as apps/argyllcms << (a,#FF00FF) >> {

}
entity "atop" as apps/atop << (a,#FF00FF) >> {

}
entity "b5i2iso" as apps/b5i2iso << (a,#FF00FF) >> {

}
entity "badwolf" as apps/badwolf << (a,#FF00FF) >> {

}
entity "bashtop" as apps/bashtop << (a,#FF00FF) >> {

}
entity "bchunk" as apps/bchunk << (a,#FF00FF) >> {

}
entity "billardgl" as apps/billardgl << (a,#FF00FF) >> {

}
entity "bind-tools" as apps/bind-tools << (a,#FF00FF) >> {

}
entity "bin2iso" as apps/bin2iso << (a,#FF00FF) >> {

}
entity "bleachbit" as apps/bleachbit << (a,#FF00FF) >> {

}
entity "bluefish" as apps/bluefish << (a,#FF00FF) >> {

}
entity "bottom" as apps/bottom << (a,#FF00FF) >> {

}
entity "brasero" as apps/brasero << (a,#FF00FF) >> {

}
entity "brave" as apps/brave << (a,#FF00FF) >> {

}
entity "brother-dcp1610w-bin" as apps/brother-dcp1610w-bin << (a,#FF00FF) >> {

}
entity "brother-scan4-bin" as apps/brother-scan4-bin << (a,#FF00FF) >> {

}
entity "cartridges" as apps/cartridges << (a,#FF00FF) >> {

}
entity "ccd2iso" as apps/ccd2iso << (a,#FF00FF) >> {

}
entity "celestia" as apps/celestia << (a,#FF00FF) >> {

}
entity "clamav" as apps/clamav << (a,#FF00FF) >> {

}
entity "cmatrix" as apps/cmatrix << (a,#FF00FF) >> {

}
entity "colord-kde" as apps/colord-kde << (a,#FF00FF) >> {

}
entity "converseen" as apps/converseen << (a,#FF00FF) >> {

}
entity "cool-retro-term" as apps/cool-retro-term << (a,#FF00FF) >> {

}
entity "coquillo" as apps/coquillo << (a,#FF00FF) >> {

}
entity "cuetools" as apps/cuetools << (a,#FF00FF) >> {

}
entity "curses-hexedit" as apps/curses-hexedit << (a,#FF00FF) >> {

}
entity "dcraw" as apps/dcraw << (a,#FF00FF) >> {

}
entity "designer" as apps/designer << (a,#FF00FF) >> {

}
entity "diffpdf" as apps/diffpdf << (a,#FF00FF) >> {

}
entity "diffuse" as apps/diffuse << (a,#FF00FF) >> {

}
entity "distrobox" as apps/distrobox << (a,#FF00FF) >> {

}
entity "dolphin-plugins-git" as apps/dolphin-plugins-git << (a,#FF00FF) >> {

}
entity "dotnet-common" as apps/dotnet-common << (a,#FF00FF) >> {

}
entity "dotnet-runtime-nugets-8" as apps/dotnet-runtime-nugets-8 << (a,#FF00FF) >> {

}
entity "drawio-desktop-bin" as apps/drawio-desktop-bin << (a,#FF00FF) >> {

}
entity "dtach" as apps/dtach << (a,#FF00FF) >> {

}
entity "dvdauthor" as apps/dvdauthor << (a,#FF00FF) >> {

}
entity "edid-tools" as apps/edid-tools << (a,#FF00FF) >> {

}
entity "elisa" as apps/elisa << (a,#FF00FF) >> {

}
entity "Email-Outlook-Message" as apps/Email-Outlook-Message << (a,#FF00FF) >> {

}
entity "erlang" as apps/erlang << (a,#FF00FF) >> {

}
entity "epiphany" as apps/epiphany << (a,#FF00FF) >> {

}
entity "epson-inkjet-printer-escpr" as apps/epson-inkjet-printer-escpr << (a,#FF00FF) >> {

}
entity "epstool" as apps/epstool << (a,#FF00FF) >> {

}
entity "eselect-emacs" as apps/eselect-emacs << (a,#FF00FF) >> {

}
entity "ext4magic" as apps/ext4magic << (a,#FF00FF) >> {

}
entity "extundelete" as apps/extundelete << (a,#FF00FF) >> {

}
entity "ffmpeg-chromium" as libs/ffmpeg-chromium << (l,#FF7700) >> {

}
entity "ffmpegthumbs" as apps/ffmpegthumbs << (a,#FF00FF) >> {

}
entity "fig2dev" as apps/fig2dev << (a,#FF00FF) >> {

}
entity "filelight" as apps/filelight << (a,#FF00FF) >> {

}
entity "firejail" as apps/firejail << (a,#FF00FF) >> {

}
entity "fish" as apps/fish << (a,#FF00FF) >> {

}
entity "flam3" as apps/flam3 << (a,#FF00FF) >> {

}
entity "flameshot" as apps/flameshot << (a,#FF00FF) >> {

}
entity "foliate" as apps/foliate << (a,#FF00FF) >> {

}
entity "fontforge" as apps/fontforge << (a,#FF00FF) >> {

}
entity "foobillard" as apps/foobillard << (a,#FF00FF) >> {

}
entity "fooyin" as apps/fooyin << (a,#FF00FF) >> {

}
entity "fpc" as apps/fpc << (a,#FF00FF) >> {

}
entity "fping" as apps/fping << (a,#FF00FF) >> {

}
entity "fraqtive" as apps/fraqtive << (a,#FF00FF) >> {

}
entity "freeoffice" as apps/freeoffice << (a,#FF00FF) >> {

}
entity "galaxy" as apps/galaxy << (a,#FF00FF) >> {

}
entity "gaupol" as apps/gaupol << (a,#FF00FF) >> {

}
entity "geany" as apps/geany << (a,#FF00FF) >> {

}
entity "geeqie" as apps/geeqie << (a,#FF00FF) >> {

}
entity "ghostwriter" as apps/ghostwriter << (a,#FF00FF) >> {

}
entity "gitkraken" as apps/gitkraken << (a,#FF00FF) >> {

}
entity "gmtp" as apps/gmtp << (a,#FF00FF) >> {

}
entity "gnofract4d" as apps/gnofract4d << (a,#FF00FF) >> {

}
entity "gnome-firmware" as apps/gnome-firmware << (a,#FF00FF) >> {

}
entity "gnome-shell-frippery" as apps/gnome-shell-frippery << (a,#FF00FF) >> {

}
entity "gnome-tweaks" as apps/gnome-tweaks << (a,#FF00FF) >> {

}
entity "gnumeric" as apps/gnumeric << (a,#FF00FF) >> {

}
entity "go" as apps/go << (a,#FF00FF) >> {

}
entity "google-chrome" as apps/google-chrome << (a,#FF00FF) >> {

}
entity "grub-btrfs" as apps/grub-btrfs << (a,#FF00FF) >> {

}
entity "gsmartcontrol" as apps/gsmartcontrol << (a,#FF00FF) >> {

}
entity "gtk-sunlight" as apps/gtk-sunlight << (a,#FF00FF) >> {

}
entity "gtkspell" as apps/gtkspell << (a,#FF00FF) >> {

}
entity "guvcview" as apps/guvcview << (a,#FF00FF) >> {

}
entity "hardinfo" as apps/hardinfo << (a,#FF00FF) >> {

}
entity "hddtemp" as apps/hddtemp << (a,#FF00FF) >> {

}
entity "htop" as apps/htop << (a,#FF00FF) >> {

}
entity "httrack" as apps/httrack << (a,#FF00FF) >> {

}
entity "hwinfo" as apps/hwinfo << (a,#FF00FF) >> {

}
entity "i2c-tools" as apps/i2c-tools << (a,#FF00FF) >> {

}
entity "iat" as apps/iat << (a,#FF00FF) >> {

}
entity "icoutils" as apps/icoutils << (a,#FF00FF) >> {

}
entity "imwheel" as apps/imwheel << (a,#FF00FF) >> {

}
entity "iotop" as apps/iotop << (a,#FF00FF) >> {

}
entity "iptraf-ng" as apps/iptraf-ng << (a,#FF00FF) >> {

}
entity "joe" as apps/joe << (a,#FF00FF) >> {

}
entity "kapptemplate" as apps/kapptemplate << (a,#FF00FF) >> {

}
entity "kate" as apps/kate << (a,#FF00FF) >> {

}
entity "kcharselect" as apps/kcharselect << (a,#FF00FF) >> {

}
entity "kchmviewer" as apps/kchmviewer << (a,#FF00FF) >> {

}
entity "kcolorchooser" as apps/kcolorchooser << (a,#FF00FF) >> {

}
entity "kdiff3" as apps/kdiff3 << (a,#FF00FF) >> {

}
entity "kdocker" as apps/kdocker << (a,#FF00FF) >> {

}
entity "keepassxc" as apps/keepassxc << (a,#FF00FF) >> {

}
entity "kgpg" as apps/kgpg << (a,#FF00FF) >> {

}
entity "khronos" as apps/khronos << (a,#FF00FF) >> {

}
entity "kimagemapeditor" as apps/kimagemapeditor << (a,#FF00FF) >> {

}
entity "kompare" as apps/kompare << (a,#FF00FF) >> {

}
entity "konqueror" as apps/konqueror << (a,#FF00FF) >> {

}
entity "kooha" as apps/kooha << (a,#FF00FF) >> {

}
entity "kookbook" as apps/kookbook << (a,#FF00FF) >> {

}
entity "krfb" as apps/krfb << (a,#FF00FF) >> {

}
entity "krecorder" as apps/krecorder << (a,#FF00FF) >> {

}
entity "kruler" as apps/kruler << (a,#FF00FF) >> {

}
entity "krusader" as apps/krusader << (a,#FF00FF) >> {

}
entity "ksnip" as apps/ksnip << (a,#FF00FF) >> {

}
entity "kvantum" as apps/kvantum << (a,#FF00FF) >> {

}
entity "leocad" as apps/leocad << (a,#FF00FF) >> {

}
entity "qalculate-gtk" as apps/qalculate-gtk << (a,#FF00FF) >> {

}
entity "qalculate-qt" as apps/qalculate-qt << (a,#FF00FF) >> {

}
entity "librecad" as apps/librecad << (a,#FF00FF) >> {

}
entity "linuxtv-utils" as apps/linuxtv-utils << (a,#FF00FF) >> {

}
entity "lshw" as apps/lshw << (a,#FF00FF) >> {

}
entity "luajit" as apps/luajit << (a,#FF00FF) >> {

}
entity "ly" as apps/ly << (a,#FF00FF) >> {

}
entity "mandelbulber" as apps/mandelbulber << (a,#FF00FF) >> {

}
entity "mangohud" as apps/mangohud << (a,#FF00FF) >> {

}
entity "marble" as apps/marble << (a,#FF00FF) >> {

}
entity "meld" as apps/meld << (a,#FF00FF) >> {

}
entity "minidlna" as apps/minidlna << (a,#FF00FF) >> {

}
entity "mono" as apps/mono << (a,#FF00FF) >> {

}
entity "mypaint-brushes" as apps/mypaint-brushes << (a,#FF00FF) >> {

}
entity "ncdu" as apps/ncdu << (a,#FF00FF) >> {

}
entity "nethogs" as apps/nethogs << (a,#FF00FF) >> {

}
entity "netkit-fingerd" as apps/netkit-fingerd << (a,#FF00FF) >> {

}
entity "nmap" as apps/nmap << (a,#FF00FF) >> {

}
entity "nmon" as apps/nmon << (a,#FF00FF) >> {

}
entity "nnn" as apps/nnn << (a,#FF00FF) >> {

}
entity "nordvpn" as apps/nordvpn << (a,#FF00FF) >> {

}
entity "nrg2iso" as apps/nrg2iso << (a,#FF00FF) >> {

}
entity "nx" as apps/nx << (a,#FF00FF) >> {

}
entity "otter" as apps/otter << (a,#FF00FF) >> {

}
entity "pandoc" as apps/pandoc << (a,#FF00FF) >> {

}
entity "pdftk" as apps/pdftk << (a,#FF00FF) >> {

}
entity "peek" as apps/peek << (a,#FF00FF) >> {

}
entity "piper" as apps/piper << (a,#FF00FF) >> {

}
entity "plasma-sdk" as apps/plasma-sdk << (a,#FF00FF) >> {

}
entity "plotutils" as apps/plotutils << (a,#FF00FF) >> {

}
entity "podofo" as apps/podofo << (a,#FF00FF) >> {

}
entity "popcorntime" as apps/popcorntime << (a,#FF00FF) >> {

}
entity "polari" as apps/polari << (a,#FF00FF) >> {

}
entity "powerpanel" as apps/powerpanel << (a,#FF00FF) >> {

}
entity "proton-ge-custom-bin" as apps/proton-ge-custom-bin << (a,#FF00FF) >> {

}
entity "pulseaudio-qt" as apps/pulseaudio-qt << (a,#FF00FF) >> {

}
entity "putty" as apps/putty << (a,#FF00FF) >> {

}
entity "pycodestyle" as apps/pycodestyle << (a,#FF00FF) >> {

}
entity "qbittorrent" as apps/qbittorrent << (a,#FF00FF) >> {

}
entity "qmplay2" as apps/qmplay2 << (a,#FF00FF) >> {

}
entity "qt5ct" as apps/qt5ct << (a,#FF00FF) >> {

}
entity "qt6ct" as apps/qt6ct << (a,#FF00FF) >> {

}
entity "quassel" as apps/quassel << (a,#FF00FF) >> {

}
entity "qhexedit2" as apps/qhexedit2 << (a,#FF00FF) >> {

}
entity "qjackctl" as apps/qjackctl << (a,#FF00FF) >> {

}
entity "qjoypad" as apps/qjoypad << (a,#FF00FF) >> {

}
entity "qview" as apps/qview << (a,#FF00FF) >> {

}
entity "rawtherapee" as apps/rawtherapee << (a,#FF00FF) >> {

}
entity "redshift" as apps/redshift << (a,#FF00FF) >> {

}
entity "rhino" as apps/rhino << (a,#FF00FF) >> {

}
entity "rssguard" as apps/rssguard << (a,#FF00FF) >> {

}
entity "rofi" as apps/rofi << (a,#FF00FF) >> {

}
entity "scapy" as apps/scapy << (a,#FF00FF) >> {

}
entity "scour" as apps/scour << (a,#FF00FF) >> {

}
entity "simple-scan" as apps/simple-scan << (a,#FF00FF) >> {

}
entity "simplescreenrecorder" as apps/simplescreenrecorder << (a,#FF00FF) >> {

}
entity "skypeforlinux" as apps/skypeforlinux << (a,#FF00FF) >> {

}
entity "snapper-gui" as apps/snapper-gui << (a,#FF00FF) >> {

}
entity "sndio" as apps/sndio << (a,#FF00FF) >> {

}
entity "solaar" as apps/solaar << (a,#FF00FF) >> {

}
entity "stress-ng" as apps/stress-ng << (a,#FF00FF) >> {

}
entity "subtitlecomposer" as apps/subtitlecomposer << (a,#FF00FF) >> {

}
entity "sqlcipher" as apps/sqlcipher << (a,#FF00FF) >> {

}
entity "supercollider" as apps/supercollider << (a,#FF00FF) >> {

}
entity "tcsh" as apps/tcsh << (a,#FF00FF) >> {

}
entity "timeshift" as apps/timeshift << (a,#FF00FF) >> {

}
entity "tophat" as apps/tophat << (a,#FF00FF) >> {

}
entity "tree" as apps/tree << (a,#FF00FF) >> {

}
entity "screen" as apps/screen << (a,#FF00FF) >> {

}
entity "shortwave" as apps/shortwave << (a,#FF00FF) >> {

}
entity "st" as apps/st << (a,#FF00FF) >> {

}
entity "sweeper" as apps/sweeper << (a,#FF00FF) >> {

}
entity "systemdgenie" as apps/systemdgenie << (a,#FF00FF) >> {

}
entity "testdisk" as apps/testdisk << (a,#FF00FF) >> {

}
entity "tk" as apps/tk << (a,#FF00FF) >> {

}
entity "tmux" as apps/tmux << (a,#FF00FF) >> {

}
entity "ttaenc" as apps/ttaenc << (a,#FF00FF) >> {

}
entity "twolame" as apps/twolame << (a,#FF00FF) >> {

}
entity "ufw" as apps/ufw << (a,#FF00FF) >> {

}
entity "ulauncher" as apps/ulauncher << (a,#FF00FF) >> {

}
entity "usb_modeswitch" as apps/usb_modeswitch << (a,#FF00FF) >> {

}
entity "usbmuxd" as apps/usbmuxd << (a,#FF00FF) >> {

}
entity "vcdimager" as apps/vcdimager << (a,#FF00FF) >> {

}
entity "vesktop" as apps/vesktop << (a,#FF00FF) >> {

}
entity "video-trimmer" as apps/video-trimmer << (a,#FF00FF) >> {

}
entity "vscodium" as apps/vscodium << (a,#FF00FF) >> {

}
entity "w_scan" as apps/w_scan << (a,#FF00FF) >> {

}
entity "wacomtablet" as apps/wacomtablet << (a,#FF00FF) >> {

}
entity "warp" as apps/warp << (a,#FF00FF) >> {

}
entity "wavemon" as apps/wavemon << (a,#FF00FF) >> {

}
entity "weechat" as apps/weechat << (a,#FF00FF) >> {

}
entity "wireshark" as apps/wireshark << (a,#FF00FF) >> {

}
entity "worker" as apps/worker << (a,#FF00FF) >> {

}
entity "xaos" as apps/xaos << (a,#FF00FF) >> {

}
entity "xli" as apps/xli << (a,#FF00FF) >> {

}
entity "xmahjongg" as apps/xmahjongg << (a,#FF00FF) >> {

}
entity "xpad" as apps/xpad << (a,#FF00FF) >> {

}
entity "xscreensavers" as apps/xscreensavers << (a,#FF00FF) >> {

}
entity "xsensors" as apps/xsensors << (a,#FF00FF) >> {

}
entity "xwininfo" as apps/xwininfo << (a,#FF00FF) >> {

}
entity "zathura" as apps/zathura << (a,#FF00FF) >> {

}
entity "zoom" as apps/zoom << (a,#FF00FF) >> {

}
entity "zsh" as apps/zsh << (a,#FF00FF) >> {

}
entity "build" as libs/build << (l,#FF7700) >> {

}
entity "cachecontrol" as libs/cachecontrol << (l,#FF7700) >> {

}
entity "cmt-plugins" as libs/cmt-plugins << (l,#FF7700) >> {

}
entity "dssi" as libs/dssi << (l,#FF7700) >> {

}
entity "gst-plugins-libnice" as libs/gst-plugins-libnice << (l,#FF7700) >> {

}
entity "libao" as libs/libao << (l,#FF7700) >> {

}
entity "libcaca" as libs/libcaca << (l,#FF7700) >> {

}
entity "libgnomecanvas" as libs/libgnomecanvas << (l,#FF7700) >> {

}
entity "liblrdf" as libs/liblrdf << (l,#FF7700) >> {

}
entity "libmediainfo" as libs/libmediainfo << (l,#FF7700) >> {

}
entity "libmikmod" as libs/libmikmod << (l,#FF7700) >> {

}
entity "libspnav" as libs/libspnav << (l,#FF7700) >> {

}
entity "lilv" as libs/lilv << (l,#FF7700) >> {

}
entity "lpeg" as libs/lpeg << (l,#FF7700) >> {

}
entity "pychromecast" as libs/pychromecast << (l,#FF7700) >> {

}
entity "rubberband" as libs/rubberband << (l,#FF7700) >> {

}
entity "tiff-compat" as libs/tiff-compat << (l,#FF7700) >> {

}
entity "xine-lib" as libs/xine-lib << (l,#FF7700) >> {

}
entity "cairo-clock" as apps/cairo-clock << (a,#FF00FF) >> {

}
entity "cairo-dock" as apps/cairo-dock << (a,#FF00FF) >> {

}
entity "cava" as apps/cava << (a,#FF00FF) >> {

}
entity "cdemu" as apps/cdemu << (a,#FF00FF) >> {

}
entity "cdemu" as layerbase/cdemu << (λ,#98FB98) >> {

}
entity "cdrdao" as apps/cdrdao << (a,#FF00FF) >> {

}
entity "chemtool" as apps/chemtool << (a,#FF00FF) >> {

}
entity "clementine" as apps/clementine << (a,#FF00FF) >> {

}
entity "cpu-x" as apps/cpu-x << (a,#FF00FF) >> {

}
entity "cutecom" as apps/cutecom << (a,#FF00FF) >> {

}
entity "darktable" as apps/darktable << (a,#FF00FF) >> {

}
entity "deadbeef" as apps/deadbeef << (a,#FF00FF) >> {

}
entity "delve" as apps/delve << (a,#FF00FF) >> {

}
entity "dia" as apps/dia << (a,#FF00FF) >> {

}
entity "diff-pdf" as apps/diff-pdf << (a,#FF00FF) >> {

}
entity "docker-tools" as apps/docker-tools << (a,#FF00FF) >> {

}
entity "dotnet-sdk-6" as apps/dotnet-sdk-6 << (a,#FF00FF) >> {

}
entity "dotnet-sdk-8" as apps/dotnet-sdk-8 << (a,#FF00FF) >> {

}
entity "easytag" as apps/easytag << (a,#FF00FF) >> {

}
entity "emacs" as apps/emacs << (a,#FF00FF) >> {

}
entity "extreme-tuxracer" as apps/extreme-tuxracer << (a,#FF00FF) >> {

}
entity "filezilla" as apps/filezilla << (a,#FF00FF) >> {

}
entity "foot" as apps/foot << (a,#FF00FF) >> {

}
entity "gftp" as apps/gftp << (a,#FF00FF) >> {

}
entity "ghostty" as apps/ghostty << (a,#FF00FF) >> {

}
entity "git-cola" as apps/git-cola << (a,#FF00FF) >> {

}
entity "gkrellm" as apps/gkrellm << (a,#FF00FF) >> {

}
entity "gnome-games" as apps/gnome-games << (a,#FF00FF) >> {

}
entity "gnuchess" as apps/gnuchess << (a,#FF00FF) >> {

}
entity "gopls" as apps/gopls << (a,#FF00FF) >> {

}
entity "goverlay" as apps/goverlay << (a,#FF00FF) >> {

}
entity "handbrake" as apps/handbrake << (a,#FF00FF) >> {

}
entity "hexchat" as apps/hexchat << (a,#FF00FF) >> {

}
entity "isomaster" as apps/isomaster << (a,#FF00FF) >> {

}
entity "kalgebra" as apps/kalgebra << (a,#FF00FF) >> {

}
entity "kget" as apps/kget << (a,#FF00FF) >> {

}
entity "kid3" as apps/kid3 << (a,#FF00FF) >> {

}
entity "krename" as apps/krename << (a,#FF00FF) >> {

}
entity "ktorrent" as apps/ktorrent << (a,#FF00FF) >> {

}
entity "kwave" as apps/kwave << (a,#FF00FF) >> {

}
entity "kweather" as apps/kweather << (a,#FF00FF) >> {

}
entity "lash" as apps/lash << (a,#FF00FF) >> {

}
entity "links" as apps/links << (a,#FF00FF) >> {

}
entity "linux-wbfs-manager" as apps/linux-wbfs-manager << (a,#FF00FF) >> {

}
entity "lutris" as apps/lutris << (a,#FF00FF) >> {

}
entity "mc" as apps/mc << (a,#FF00FF) >> {

}
entity "milkytracker" as apps/milkytracker << (a,#FF00FF) >> {

}
entity "minicom" as apps/minicom << (a,#FF00FF) >> {

}
entity "mirage2iso" as apps/mirage2iso << (a,#FF00FF) >> {

}
entity "mkvtoolnix" as apps/mkvtoolnix << (a,#FF00FF) >> {

}
entity "mosh" as apps/mosh << (a,#FF00FF) >> {

}
entity "mpv" as apps/mpv << (a,#FF00FF) >> {

}
entity "musescore" as apps/musescore << (a,#FF00FF) >> {

}
entity "net-snmp" as apps/net-snmp << (a,#FF00FF) >> {

}
entity "nwipe" as apps/nwipe << (a,#FF00FF) >> {

}
entity "obs-studio" as apps/obs-studio << (a,#FF00FF) >> {

}
entity "oh-my-posh" as apps/oh-my-posh << (a,#FF00FF) >> {

}
entity "okteta" as apps/okteta << (a,#FF00FF) >> {

}
entity "openjade" as apps/openjade << (a,#FF00FF) >> {

}
entity "openrgb" as apps/openrgb << (a,#FF00FF) >> {

}
entity "opera" as apps/opera << (a,#FF00FF) >> {

}
entity "oversteer" as apps/oversteer << (a,#FF00FF) >> {

}
entity "p7zip-ui" as apps/p7zip-ui << (a,#FF00FF) >> {

}
entity "pcem" as apps/pcem << (a,#FF00FF) >> {

}
entity "pdfarranger" as apps/pdfarranger << (a,#FF00FF) >> {

}
entity "picom" as apps/picom << (a,#FF00FF) >> {

}
entity "pip" as apps/pip << (a,#FF00FF) >> {

}
entity "plymouth-kcm" as apps/plymouth-kcm << (a,#FF00FF) >> {

}
entity "postgresql" as apps/postgresql << (a,#FF00FF) >> {

}
entity "pstoedit" as apps/pstoedit << (a,#FF00FF) >> {

}
entity "qcad" as apps/qcad << (a,#FF00FF) >> {

}
entity "qdevicemonitor" as apps/qdevicemonitor << (a,#FF00FF) >> {

}
entity "qmmp" as apps/qmmp << (a,#FF00FF) >> {

}
entity "qtox" as apps/qtox << (a,#FF00FF) >> {

}
entity "qutebrowser" as apps/qutebrowser << (a,#FF00FF) >> {

}
entity "regexxer" as apps/regexxer << (a,#FF00FF) >> {

}
entity "remmina" as apps/remmina << (a,#FF00FF) >> {

}
entity "rotoscope" as apps/rotoscope << (a,#FF00FF) >> {

}
entity "shntool" as apps/shntool << (a,#FF00FF) >> {

}
entity "shutter" as apps/shutter << (a,#FF00FF) >> {

}
entity "sigil" as apps/sigil << (a,#FF00FF) >> {

}
entity "smplayer" as apps/smplayer << (a,#FF00FF) >> {

}
entity "soundconverter" as apps/soundconverter << (a,#FF00FF) >> {

}
entity "sqliteman" as apps/sqliteman << (a,#FF00FF) >> {

}
entity "tesseract" as apps/tesseract << (a,#FF00FF) >> {

}
entity "tigervnc" as apps/tigervnc << (a,#FF00FF) >> {

}
entity "tor" as apps/tor << (a,#FF00FF) >> {

}
entity "transmission" as apps/transmission << (a,#FF00FF) >> {

}
entity "upplay" as apps/upplay << (a,#FF00FF) >> {

}
entity "vdr" as apps/vdr << (a,#FF00FF) >> {

}
entity "visual-regexp" as apps/visual-regexp << (a,#FF00FF) >> {

}
entity "vivaldi" as apps/vivaldi << (a,#FF00FF) >> {

}
entity "vkeybd" as apps/vkeybd << (a,#FF00FF) >> {

}
entity "warzone2100" as apps/warzone2100 << (a,#FF00FF) >> {

}
entity "wxhexeditor" as apps/wxhexeditor << (a,#FF00FF) >> {

}
entity "wine-staging" as apps/wine-staging << (a,#FF00FF) >> {

}
entity "yamllint" as apps/yamllint << (a,#FF00FF) >> {

}
entity "indilib" as libs/indilib << (l,#FF7700) >> {

}
entity "openvdb" as libs/openvdb << (l,#FF7700) >> {

}
entity "amsynth" as apps/amsynth << (a,#FF00FF) >> {

}
entity "asbru-cm" as apps/asbru-cm << (a,#FF00FF) >> {

}
entity "avalonia-ilspy" as apps/avalonia-ilspy << (a,#FF00FF) >> {

}
entity "avidemux" as apps/avidemux << (a,#FF00FF) >> {

}
entity "bat" as apps/bat << (a,#FF00FF) >> {

}
entity "brother-dcp1610w-bin-brscan4" as apps/brother-dcp1610w-bin-brscan4 << (a,#FF00FF) >> {

}
entity "calibre" as apps/calibre << (a,#FF00FF) >> {

}
entity "cantor" as apps/cantor << (a,#FF00FF) >> {

}
entity "celluloid" as apps/celluloid << (a,#FF00FF) >> {

}
entity "clamtk" as apps/clamtk << (a,#FF00FF) >> {

}
entity "dvd-rw-tools" as apps/dvd-rw-tools << (a,#FF00FF) >> {

}
entity "fluidsynth" as apps/fluidsynth << (a,#FF00FF) >> {

}
entity "fotocx" as apps/fotocx << (a,#FF00FF) >> {

}
entity "gnome-nettool" as apps/gnome-nettool << (a,#FF00FF) >> {

}
entity "gnuplot" as apps/gnuplot << (a,#FF00FF) >> {

}
entity "helm-synthesizer" as apps/helm-synthesizer << (a,#FF00FF) >> {

}
entity "hplip" as apps/hplip << (a,#FF00FF) >> {

}
entity "k3b" as apps/k3b << (a,#FF00FF) >> {

}
entity "kdegames" as apps/kdegames << (a,#FF00FF) >> {

}
entity "kodi" as apps/kodi << (a,#FF00FF) >> {

}
entity "lazarus" as apps/lazarus << (a,#FF00FF) >> {

}
entity "libreoffice" as apps/libreoffice << (a,#FF00FF) >> {

}
entity "lollypop" as apps/lollypop << (a,#FF00FF) >> {

}
entity "luminance-hdr" as apps/luminance-hdr << (a,#FF00FF) >> {

}
entity "mediainfo" as apps/mediainfo << (a,#FF00FF) >> {

}
entity "mediainfo-gui" as apps/mediainfo-gui << (a,#FF00FF) >> {

}
entity "megasync" as apps/megasync << (a,#FF00FF) >> {

}
entity "mixxx" as apps/mixxx << (a,#FF00FF) >> {

}
entity "nagios" as apps/nagios << (a,#FF00FF) >> {

}
entity "neovim" as apps/neovim << (a,#FF00FF) >> {

}
entity "nmapsi" as apps/nmapsi << (a,#FF00FF) >> {

}
entity "onedrive" as apps/onedrive << (a,#FF00FF) >> {

}
entity "openra" as apps/openra << (a,#FF00FF) >> {

}
entity "plasma-firewall" as apps/plasma-firewall << (a,#FF00FF) >> {

}
entity "q4wine" as apps/q4wine << (a,#FF00FF) >> {

}
entity "qsampler" as apps/qsampler << (a,#FF00FF) >> {

}
entity "quodlibet" as apps/quodlibet << (a,#FF00FF) >> {

}
entity "rclone" as apps/rclone << (a,#FF00FF) >> {

}
entity "rosegarden" as apps/rosegarden << (a,#FF00FF) >> {

}
entity "scribus" as apps/scribus << (a,#FF00FF) >> {

}
entity "skanpage" as apps/skanpage << (a,#FF00FF) >> {

}
entity "sqlitebrowser" as apps/sqlitebrowser << (a,#FF00FF) >> {

}
entity "terminatorx" as apps/terminatorx << (a,#FF00FF) >> {

}
entity "timidity" as apps/timidity << (a,#FF00FF) >> {

}
entity "tokodon" as apps/tokodon << (a,#FF00FF) >> {

}
entity "valgrind" as apps/valgrind << (a,#FF00FF) >> {

}
entity "x2goclient" as apps/x2goclient << (a,#FF00FF) >> {

}
entity "x2goserver" as apps/x2goserver << (a,#FF00FF) >> {

}
entity "xemacs" as apps/xemacs << (a,#FF00FF) >> {

}
entity "xmms2" as apps/xmms2 << (a,#FF00FF) >> {

}
entity "xscreensaver" as apps/xscreensaver << (a,#FF00FF) >> {

}
entity "xournal" as apps/xournal << (a,#FF00FF) >> {

}
entity "yoshimi" as apps/yoshimi << (a,#FF00FF) >> {

}
entity "zynaddsubfx" as apps/zynaddsubfx << (a,#FF00FF) >> {

}
entity "farstream" as libs/farstream << (l,#FF7700) >> {

}
entity "sdl" as libs/sdl << (l,#FF7700) >> {

}
entity "sdl2" as libs/sdl2 << (l,#FF7700) >> {

}
entity "audacious" as apps/audacious << (a,#FF00FF) >> {

}
entity "calf" as apps/calf << (a,#FF00FF) >> {

}
entity "calligra" as apps/calligra << (a,#FF00FF) >> {

}
entity "dosbox" as apps/dosbox << (a,#FF00FF) >> {

}
entity "flacon" as apps/flacon << (a,#FF00FF) >> {

}
entity "gcdemu" as apps/gcdemu << (a,#FF00FF) >> {

}
entity "goneovim" as apps/goneovim << (a,#FF00FF) >> {

}
entity "gradience" as apps/gradience << (a,#FF00FF) >> {

}
entity "hugin" as apps/hugin << (a,#FF00FF) >> {

}
entity "inkscape" as apps/inkscape << (a,#FF00FF) >> {

}
entity "kcdemu" as apps/kcdemu << (a,#FF00FF) >> {

}
entity "kstars" as apps/kstars << (a,#FF00FF) >> {

}
entity "ktimetracker" as apps/ktimetracker << (a,#FF00FF) >> {

}
entity "labplot" as apps/labplot << (a,#FF00FF) >> {

}
entity "nomacs" as apps/nomacs << (a,#FF00FF) >> {

}
entity "octave" as apps/octave << (a,#FF00FF) >> {

}
entity "pidgin" as apps/pidgin << (a,#FF00FF) >> {

}
entity "qsynth" as apps/qsynth << (a,#FF00FF) >> {

}
entity "RcloneBrowser" as apps/RcloneBrowser << (a,#FF00FF) >> {

}
entity "stellarium" as apps/stellarium << (a,#FF00FF) >> {

}
entity "mlt" as libs/mlt << (l,#FF7700) >> {

}
entity "pygame" as libs/pygame << (l,#FF7700) >> {

}
entity "suil" as libs/suil << (l,#FF7700) >> {

}
entity "cmus" as apps/cmus << (a,#FF00FF) >> {

}
entity "digikam" as apps/digikam << (a,#FF00FF) >> {

}
entity "graphviz" as apps/graphviz << (a,#FF00FF) >> {

}
entity "hedgewars" as apps/hedgewars << (a,#FF00FF) >> {

}
entity "kdenlive" as apps/kdenlive << (a,#FF00FF) >> {

}
entity "neverball" as apps/neverball << (a,#FF00FF) >> {

}
entity "nut" as apps/nut << (a,#FF00FF) >> {

}
entity "warmux" as apps/warmux << (a,#FF00FF) >> {

}
entity "gtkmm" as libs/gtkmm << (l,#FF7700) >> {

}
entity "libmypaint" as libs/libmypaint << (l,#FF7700) >> {

}
entity "audacity" as apps/audacity << (a,#FF00FF) >> {

}
entity "conky" as apps/conky << (a,#FF00FF) >> {

}
entity "deluge" as apps/deluge << (a,#FF00FF) >> {

}
entity "doxygen" as apps/doxygen << (a,#FF00FF) >> {

}
entity "gimp" as apps/gimp << (a,#FF00FF) >> {

}
entity "logitech-linux-rpm-led" as apps/logitech-linux-rpm-led << (a,#FF00FF) >> {

}
entity "lyx" as apps/lyx << (a,#FF00FF) >> {

}
entity "museseq" as apps/museseq << (a,#FF00FF) >> {

}
entity "mypaint" as apps/mypaint << (a,#FF00FF) >> {

}
entity "plantuml" as apps/plantuml << (a,#FF00FF) >> {

}
entity "ocio-oiio" as libs/ocio-oiio << (l,#FF7700) >> {

}
entity "wxpython" as libs/wxpython << (l,#FF7700) >> {

}
entity "ardour" as apps/ardour << (a,#FF00FF) >> {

}
entity "easyeffects" as apps/easyeffects << (a,#FF00FF) >> {

}
entity "krita" as apps/krita << (a,#FF00FF) >> {

}
entity "qtractor" as apps/qtractor << (a,#FF00FF) >> {

}
entity "seq24" as apps/seq24 << (a,#FF00FF) >> {

}
entity "xsane" as apps/xsane << (a,#FF00FF) >> {

}
entity "blender" as apps/blender << (a,#FF00FF) >> {

}
entity "displaycal-py3" as apps/displaycal-py3 << (a,#FF00FF) >> {

}
entity "kdevelop" as apps/kdevelop << (a,#FF00FF) >> {

}
entity "umbrello" as apps/umbrello << (a,#FF00FF) >> {

}


"apps/oh-my-posh" --u--> "fonts/fontawesome"
"apps/x2goserver" --u--> "fonts/font-cursor-misc"
"apps/mangohud" --u--> "fonts/lato"
"apps/kodi" --u--> "fonts/roboto"
"apps/zynaddsubfx" --u--> "fonts/roboto"
"apps/hedgewars" --u--> "fonts/wqy-zenhei"
"apps/neverball" --u--> "fonts/wqy-microhei"
"apps/lutris" --u--> "fonts/fluid-soundfont"
"apps/kalgebra" --u--> "libs/analitza"
"apps/cantor" --u--> "libs/analitza"
"apps/darktable" --u--> "libs/AOMediaCodecs"
"apps/handbrake" --u--> "libs/AOMediaCodecs"
"apps/links" --u--> "libs/AOMediaCodecs"
"libs/sdl2" --u--> "libs/AOMediaCodecs"
"apps/ardour" --u--> "libs/aubio"
"apps/qtractor" --u--> "libs/aubio"
"libs/libmypaint" --u--> "libs/babl-gegl"
"apps/lutris" --u--> "libs/beautifulsoup4"
"apps/qutebrowser" --u--> "libs/beautifulsoup4"
"apps/calibre" --u--> "libs/beautifulsoup4"
"apps/lollypop" --u--> "libs/beautifulsoup4"
"libs/indilib" --u--> "libs/cfitsio"
"apps/luminance-hdr" --u--> "libs/cfitsio"
"apps/labplot" --u--> "libs/cfitsio"
"apps/qutebrowser" --u--> "libs/chrome-binary-plugins"
"apps/vivaldi" --u--> "libs/chrome-binary-plugins"
"apps/pip" --u--> "libs/colorama"
"apps/qutebrowser" --u--> "libs/colorama"
"apps/openrgb" --u--> "libs/cpp-httplib"
"libs/indilib" --u--> "libs/cpp-httplib"
"apps/sigil" --u--> "libs/css-parser"
"apps/calibre" --u--> "libs/css-parser"
"apps/sigil" --u--> "libs/cssselect"
"apps/inkscape" --u--> "libs/cssselect"
"apps/calibre" --u--> "libs/feedparser"
"apps/quodlibet" --u--> "libs/feedparser"
"apps/tigervnc" --u--> "libs/fltk"
"apps/yoshimi" --u--> "libs/fltk"
"apps/zynaddsubfx" --u--> "libs/fltk"
"apps/octave" --u--> "libs/fltk"
"apps/megasync" --u--> "libs/freeimage"
"apps/nagios" --u--> "apps/freeradius-client"
"libs/libcaca" --u--> "libs/ftgl"
"apps/xmms2" --u--> "libs/game-music-emu"
"apps/octave" --u--> "libs/gl2ps"
"apps/mangohud" --u--> "libs/glfw"
"apps/cpu-x" --u--> "libs/glfw"
"libs/openvdb" --u--> "libs/glfw"
"apps/shutter" --u--> "libs/goocanvas"
"apps/emacs" --u--> "libs/gpm"
"apps/links" --u--> "libs/gpm"
"apps/mc" --u--> "libs/gpm"
"apps/xemacs" --u--> "libs/gpm"
"libs/farstream" --u--> "libs/gst-plugins-srtp"
"apps/pidgin" --u--> "libs/gst-plugins-v4l2"
"apps/regexxer" --u--> "libs/gtksourceviewmm"
"libs/gst-plugins-libnice" --u--> "libs/gupnp-igd"
"libs/farstream" --u--> "libs/gupnp-igd"
"apps/openrgb" --u--> "libs/hidapi"
"apps/mixxx" --u--> "libs/hidapi"
"apps/logitech-linux-rpm-led" --u--> "libs/hidapi"
"apps/easytag" --u--> "libs/id3lib"
"apps/kid3" --u--> "libs/id3lib"
"apps/kwave" --u--> "libs/id3lib"
"apps/cava" --u--> "libs/iniparser"
"apps/isomaster" --u--> "libs/iniparser"
"apps/obs-studio" --u--> "libs/intel-mediasdk"
"apps/mosh" --u--> "libs/IO-Tty"
"apps/asbru-cm" --u--> "libs/IO-Tty"
"libs/tiff-compat" --u--> "libs/jbigkit"
"libs/cmt-plugins" --u--> "libs/ladspa-sdk"
"libs/dssi" --u--> "libs/ladspa-sdk"
"libs/liblrdf" --u--> "libs/ladspa-sdk"
"libs/rubberband" --u--> "libs/ladspa-sdk"
"apps/fluidsynth" --u--> "libs/ladspa-sdk"
"apps/qsampler" --u--> "libs/ladspa-sdk"
"apps/rosegarden" --u--> "libs/ladspa-sdk"
"apps/terminatorx" --u--> "libs/ladspa-sdk"
"libs/mlt" --u--> "libs/ladspa-sdk"
"apps/museseq" --u--> "libs/ladspa-sdk"
"apps/easyeffects" --u--> "libs/ladspa-sdk"
"apps/qtractor" --u--> "libs/ladspa-sdk"
"apps/tesseract" --u--> "libs/leptonica"
"apps/blender" --u--> "libs/lib3ds"
"apps/audacious" --u--> "libs/libbs2b"
"apps/easyeffects" --u--> "libs/libbs2b"
"apps/gnuplot" --u--> "libs/libcerf"
"apps/labplot" --u--> "libs/libcerf"
"apps/fotocx" --u--> "libs/libchamplain"
"apps/nwipe" --u--> "libs/libconfig"
"apps/picom" --u--> "libs/libconfig"
"apps/xmms2" --u--> "libs/libdiscid"
"apps/cmus" --u--> "libs/libdiscid"
"apps/deadbeef" --u--> "libs/libdispatch"
"apps/fooyin" --u--> "libs/libebur128"
"apps/mixxx" --u--> "libs/libebur128"
"libs/mlt" --u--> "libs/libebur128"
"apps/easyeffects" --u--> "libs/libebur128"
"apps/chemtool" --u--> "libs/libemf"
"apps/pstoedit" --u--> "libs/libemf"
"apps/gnuplot" --u--> "libs/libgii"
"libs/libgnomecanvas" --u--> "libs/libglade"
"apps/cairo-clock" --u--> "libs/libglade"
"apps/gnome-games" --u--> "libs/libglade"
"apps/linux-wbfs-manager" --u--> "libs/libglade"
"apps/rotoscope" --u--> "libs/libglade"
"apps/blender" --u--> "libs/libharu"
"apps/kget" --u--> "libs/libktorrent"
"apps/ktorrent" --u--> "libs/libktorrent"
"libs/dssi" --u--> "libs/liblo"
"apps/amsynth" --u--> "libs/liblo"
"apps/rosegarden" --u--> "libs/liblo"
"apps/zynaddsubfx" --u--> "libs/liblo"
"apps/museseq" --u--> "libs/liblo"
"apps/ardour" --u--> "libs/liblo"
"apps/easyeffects" --u--> "libs/liblo"
"apps/qtractor" --u--> "libs/liblo"
"apps/digikam" --u--> "libs/liblqr"
"apps/cdemu" --u--> "libs/libmirage"
"layerbase/cdemu" --u--> "libs/libmirage"
"apps/mirage2iso" --u--> "libs/libmirage"
"apps/kid3" --u--> "libs/libmp4v2"
"apps/avidemux" --u--> "libs/libmp4v2"
"apps/cmus" --u--> "libs/libmp4v2"
"apps/musescore" --u--> "libs/libopusenc"
"apps/clementine" --u--> "libs/libprojectm"
"apps/qmmp" --u--> "libs/libprojectm"
"apps/extreme-tuxracer" --u--> "libs/libsfml"
"apps/xmms2" --u--> "libs/libshout"
"apps/xmms2" --u--> "libs/libsidplay"
"apps/audacious" --u--> "libs/libsidplayfp"
"apps/mixxx" --u--> "libs/libsoundtouch"
"apps/audacity" --u--> "libs/libsoundtouch"
"apps/ardour" --u--> "libs/libsoundtouch"
"apps/easyeffects" --u--> "libs/libsoundtouch"
"apps/foot" --u--> "libs/libutf8proc"
"apps/neovim" --u--> "libs/libutf8proc"
"apps/libreoffice" --u--> "libs/libvisio"
"apps/scribus" --u--> "libs/libvisio"
"apps/calligra" --u--> "libs/libvisio"
"apps/inkscape" --u--> "libs/libvisio"
"apps/xemacs" --u--> "libs/libXaw3d"
"apps/cutecom" --u--> "libs/lrzsz"
"apps/minicom" --u--> "libs/lrzsz"
"apps/dotnet-sdk-6" --u--> "libs/lttng-ust-2_12"
"apps/dotnet-sdk-8" --u--> "libs/lttng-ust-2_12"
"apps/neovim" --u--> "libs/LuaBitOp"
"libs/lilv" --u--> "libs/lv2"
"apps/amsynth" --u--> "libs/lv2"
"apps/helm-synthesizer" --u--> "libs/lv2"
"apps/qsampler" --u--> "libs/lv2"
"apps/yoshimi" --u--> "libs/lv2"
"apps/calf" --u--> "libs/lv2"
"libs/suil" --u--> "libs/lv2"
"apps/links" --u--> "libs/lzip"
"apps/shntool" --u--> "libs/mac"
"apps/xmms2" --u--> "libs/mac"
"apps/sigil" --u--> "libs/mathjax"
"apps/calibre" --u--> "libs/mathjax"
"apps/obs-studio" --u--> "libs/mbedtls"
"apps/openrgb" --u--> "libs/mbedtls"
"apps/transmission" --u--> "libs/mbedtls"
"apps/xemacs" --u--> "libs/motif"
"apps/xscreensaver" --u--> "libs/motif"
"apps/yoshimi" --u--> "libs/mxml"
"apps/zynaddsubfx" --u--> "libs/mxml"
"libs/libao" --u--> "libs/nas"
"libs/libmikmod" --u--> "libs/nas"
"apps/timidity" --u--> "libs/nas"
"apps/xemacs" --u--> "libs/nas"
"apps/xemacs" --u--> "libs/neXtaw"
"apps/mangohud" --u--> "libs/nlohmann_json"
"apps/mkvtoolnix" --u--> "libs/nlohmann_json"
"apps/obs-studio" --u--> "libs/nlohmann_json"
"apps/openrgb" --u--> "libs/nlohmann_json"
"libs/indilib" --u--> "libs/nlohmann_json"
"apps/easyeffects" --u--> "libs/nlohmann_json"
"apps/ghostty" --u--> "libs/oniguruma"
"apps/bat" --u--> "libs/oniguruma"
"apps/postgresql" --u--> "libs/ossp-uuid"
"apps/asbru-cm" --u--> "libs/ossp-uuid"
"apps/warzone2100" --u--> "libs/physfs"
"apps/graphviz" --u--> "libs/physfs"
"apps/hedgewars" --u--> "libs/physfs"
"apps/neverball" --u--> "libs/physfs"
"apps/audacity" --u--> "libs/portsmf"
"libs/build" --u--> "libs/pyproject-hooks"
"apps/pip" --u--> "libs/pyproject-hooks"
"libs/cachecontrol" --u--> "libs/python-msgpack"
"apps/calibre" --u--> "libs/python-msgpack"
"libs/pychromecast" --u--> "libs/python-protobuf"
"apps/lutris" --u--> "libs/python-protobuf"
"apps/mypaint" --u--> "libs/python-protobuf"
"apps/sqlitebrowser" --u--> "libs/qcustomplot"
"apps/octave" --u--> "libs/qscintilla"
"apps/sqliteman" --u--> "libs/qscintilla-qt5"
"apps/sqlitebrowser" --u--> "libs/qscintilla-qt5"
"apps/git-cola" --u--> "libs/qtpy"
"apps/kdegames" --u--> "libs/qtpy"
"apps/labplot" --u--> "libs/qxlsx"
"apps/stellarium" --u--> "libs/qxlsx"
"apps/kodi" --u--> "libs/rapidjson"
"apps/octave" --u--> "libs/rapidjson"
"apps/audacity" --u--> "libs/rapidjson"
"apps/sigil" --u--> "libs/regex"
"apps/calibre" --u--> "libs/regex"
"apps/gradience" --u--> "libs/regex"
"apps/hplip" --u--> "libs/reportlab"
"apps/gradience" --u--> "libs/reportlab"
"apps/obs-studio" --u--> "apps/rnnoise"
"apps/easyeffects" --u--> "apps/rnnoise"
"libs/mlt" --u--> "libs/rtaudio"
"apps/museseq" --u--> "libs/rtaudio"
"apps/milkytracker" --u--> "libs/rtmidi"
"apps/git-cola" --u--> "libs/send2trash"
"apps/displaycal-py3" --u--> "libs/send2trash"
"apps/openjade" --u--> "libs/sgml-common"
"apps/tor" --u--> "libs/sgml-common"
"libs/sdl" --u--> "libs/smpeg"
"libs/pygame" --u--> "libs/smpeg2"
"libs/openvdb" --u--> "libs/tbb"
"apps/stellarium" --u--> "libs/tbb"
"apps/easyeffects" --u--> "libs/tbb"
"libs/libmediainfo" --u--> "libs/tinyxml2"
"apps/musescore" --u--> "libs/tinyxml2"
"apps/kodi" --u--> "libs/tinyxml2"
"apps/emacs" --u--> "libs/tree-sitter"
"apps/neovim" --u--> "libs/tree-sitter"
"apps/kdegames" --u--> "libs/twisted"
"apps/deluge" --u--> "libs/twisted"
"apps/obs-studio" --u--> "libs/uthash"
"apps/picom" --u--> "libs/uthash"
"apps/mkvtoolnix" --u--> "libs/utfcpp"
"libs/rubberband" --u--> "libs/vamp-plugin-sdk"
"apps/audacity" --u--> "libs/vamp-plugin-sdk"
"apps/obs-studio" --u--> "libs/websocketpp"
"libs/indilib" --u--> "libs/websocketpp"
"apps/pdfarranger" --u--> "libs/python-deprecated"
"apps/calibre" --u--> "libs/python-deprecated"
"apps/wine-staging" --u--> "libs/vdf"
"apps/diff-pdf" --u--> "libs/wxGTK"
"apps/filezilla" --u--> "libs/wxGTK"
"apps/pcem" --u--> "libs/wxGTK"
"apps/wxhexeditor" --u--> "libs/wxGTK"
"apps/gnuplot" --u--> "libs/wxGTK"
"apps/mediainfo-gui" --u--> "libs/wxGTK"
"apps/hugin" --u--> "libs/wxGTK"
"apps/audacity" --u--> "libs/wxGTK"
"libs/wxpython" --u--> "libs/wxGTK"
"apps/p7zip-ui" --u--> "libs/wxGTK-3_0-gtk3"
"apps/oversteer" --u--> "libs/xsimd"
"apps/krita" --u--> "libs/xsimd"
"apps/handbrake" --u--> "libs/zimg"
"apps/easyeffects" --u--> "libs/zita-convolver"
"apps/qdevicemonitor" --u--> "apps/android-tools"
"apps/libreoffice" --u--> "apps/ant"
"apps/plantuml" --u--> "apps/ant"
"apps/kdevelop" --u--> "apps/astyle"
"apps/conky" --u--> "apps/apcupsd"
"apps/displaycal-py3" --u--> "apps/argyllcms"
"apps/gnome-nettool" --u--> "apps/bind-tools"
"apps/nagios" --u--> "apps/bind-tools"
"apps/nmapsi" --u--> "apps/bind-tools"
"apps/brother-dcp1610w-bin-brscan4" --u--> "apps/brother-scan4-bin"
"apps/clamtk" --u--> "apps/clamav"
"apps/fotocx" --u--> "apps/dcraw"
"apps/hugin" --u--> "apps/dcraw"
"apps/museseq" --u--> "apps/designer"
"apps/dotnet-sdk-6" --u--> "apps/dotnet-common"
"apps/dotnet-sdk-8" --u--> "apps/dotnet-common"
"apps/dotnet-sdk-8" --u--> "apps/dotnet-runtime-nugets-8"
"apps/octave" --u--> "apps/epstool"
"apps/emacs" --u--> "apps/eselect-emacs"
"apps/xemacs" --u--> "apps/eselect-emacs"
"apps/opera" --u--> "libs/ffmpeg-chromium"
"apps/vivaldi" --u--> "libs/ffmpeg-chromium"
"apps/chemtool" --u--> "apps/fig2dev"
"apps/octave" --u--> "apps/fig2dev"
"apps/libreoffice" --u--> "apps/fontforge"
"apps/lazarus" --u--> "apps/fpc"
"apps/nagios" --u--> "apps/fping"
"apps/lyx" --u--> "apps/gnumeric"
"apps/delve" --u--> "apps/go"
"apps/gopls" --u--> "apps/go"
"apps/rclone" --u--> "apps/go"
"apps/gkrellm" --u--> "apps/hddtemp"
"apps/conky" --u--> "apps/hddtemp"
"apps/nut" --u--> "apps/i2c-tools"
"apps/q4wine" --u--> "apps/icoutils"
"apps/kdevelop" --u--> "apps/kapptemplate"
"libs/lpeg" --u--> "apps/luajit"
"apps/mpv" --u--> "apps/luajit"
"apps/obs-studio" --u--> "apps/luajit"
"apps/cantor" --u--> "apps/luajit"
"apps/neovim" --u--> "apps/luajit"
"apps/tokodon" --u--> "apps/luajit"
"apps/goverlay" --u--> "apps/mangohud"
"apps/gimp" --u--> "apps/mypaint-brushes"
"apps/mypaint" --u--> "apps/mypaint-brushes"
"apps/gnome-nettool" --u--> "apps/netkit-fingerd"
"apps/gnome-nettool" --u--> "apps/nmap"
"apps/nmapsi" --u--> "apps/nmap"
"apps/x2goclient" --u--> "apps/nx"
"apps/x2goserver" --u--> "apps/nx"
"apps/pstoedit" --u--> "apps/plotutils"
"apps/krename" --u--> "apps/podofo"
"apps/calibre" --u--> "apps/podofo"
"apps/scribus" --u--> "apps/podofo"
"apps/kdevelop" --u--> "apps/pycodestyle"
"apps/sqlitebrowser" --u--> "apps/qhexedit2"
"apps/inkscape" --u--> "apps/scour"
"apps/cava" --u--> "apps/sndio"
"apps/qtox" --u--> "apps/sqlcipher"
"apps/visual-regexp" --u--> "apps/tk"
"apps/vkeybd" --u--> "apps/tk"
"apps/timidity" --u--> "apps/tk"
"apps/vdr" --u--> "apps/twolame"
"apps/avidemux" --u--> "apps/twolame"
"apps/audacity" --u--> "apps/twolame"
"apps/plasma-firewall" --u--> "apps/ufw"
"apps/qdevicemonitor" --u--> "apps/usbmuxd"
"apps/calibre" --u--> "apps/usbmuxd"
"libs/xine-lib" --u--> "apps/vcdimager"
"apps/k3b" --u--> "apps/vcdimager"
"apps/x2goserver" --u--> "apps/xwininfo"
"apps/xscreensaver" --u--> "apps/xwininfo"
"apps/gradience" --u--> "libs/build"
"apps/displaycal-py3" --u--> "libs/build"
"apps/pip" --u--> "libs/cachecontrol"
"apps/inkscape" --u--> "libs/cachecontrol"
"apps/qmmp" --u--> "libs/cmt-plugins"
"apps/fluidsynth" --u--> "libs/cmt-plugins"
"apps/terminatorx" --u--> "libs/cmt-plugins"
"apps/amsynth" --u--> "libs/dssi"
"apps/qsampler" --u--> "libs/dssi"
"apps/rosegarden" --u--> "libs/dssi"
"apps/zynaddsubfx" --u--> "libs/dssi"
"apps/museseq" --u--> "libs/dssi"
"apps/qtractor" --u--> "libs/dssi"
"libs/farstream" --u--> "libs/gst-plugins-libnice"
"apps/cdemu" --u--> "libs/libao"
"layerbase/cdemu" --u--> "libs/libao"
"apps/cdrdao" --u--> "libs/libao"
"apps/kodi" --u--> "libs/libao"
"apps/timidity" --u--> "libs/libao"
"apps/xmms2" --u--> "libs/libao"
"apps/cmus" --u--> "libs/libao"
"libs/xine-lib" --u--> "libs/libcaca"
"apps/gnuplot" --u--> "libs/libcaca"
"apps/xournal" --u--> "libs/libgnomecanvas"
"apps/rosegarden" --u--> "libs/liblrdf"
"apps/terminatorx" --u--> "libs/liblrdf"
"apps/museseq" --u--> "libs/liblrdf"
"apps/ardour" --u--> "libs/liblrdf"
"apps/mediainfo" --u--> "libs/libmediainfo"
"apps/megasync" --u--> "libs/libmediainfo"
"libs/sdl" --u--> "libs/libmikmod"
"apps/cmus" --u--> "libs/libmikmod"
"apps/blender" --u--> "libs/libspnav"
"apps/audacity" --u--> "libs/lilv"
"apps/museseq" --u--> "libs/lilv"
"apps/ardour" --u--> "libs/lilv"
"apps/easyeffects" --u--> "libs/lilv"
"apps/qtractor" --u--> "libs/lilv"
"apps/neovim" --u--> "libs/lpeg"
"apps/displaycal-py3" --u--> "libs/pychromecast"
"apps/mixxx" --u--> "libs/rubberband"
"libs/mlt" --u--> "libs/rubberband"
"apps/museseq" --u--> "libs/rubberband"
"apps/ardour" --u--> "libs/rubberband"
"apps/qtractor" --u--> "libs/rubberband"
"apps/goneovim" --u--> "libs/tiff-compat"
"apps/vdr" --u--> "libs/xine-lib"
"apps/quodlibet" --u--> "libs/xine-lib"
"libs/mlt" --u--> "libs/xine-lib"
"apps/gcdemu" --u--> "apps/cdemu"
"apps/kcdemu" --u--> "apps/cdemu"
"apps/k3b" --u--> "apps/cdrdao"
"apps/lyx" --u--> "apps/dia"
"apps/openra" --u--> "apps/dotnet-sdk-6"
"apps/avalonia-ilspy" --u--> "apps/dotnet-sdk-8"
"apps/kdegames" --u--> "apps/gnuchess"
"apps/vkeybd" --u--> "apps/lash"
"apps/amsynth" --u--> "apps/lash"
"apps/fluidsynth" --u--> "apps/lash"
"apps/zynaddsubfx" --u--> "apps/lash"
"apps/calf" --u--> "apps/lash"
"apps/museseq" --u--> "apps/lash"
"apps/seq24" --u--> "apps/lash"
"apps/asbru-cm" --u--> "apps/mosh"
"apps/smplayer" --u--> "apps/mpv"
"apps/celluloid" --u--> "apps/mpv"
"apps/tokodon" --u--> "apps/mpv"
"apps/hplip" --u--> "apps/net-snmp"
"apps/nagios" --u--> "apps/net-snmp"
"apps/nut" --u--> "apps/net-snmp"
"apps/calligra" --u--> "apps/pstoedit"
"apps/octave" --u--> "apps/pstoedit"
"apps/skanpage" --u--> "apps/tesseract"
"apps/asbru-cm" --u--> "apps/tigervnc"
"apps/kstars" --u--> "libs/indilib"
"apps/stellarium" --u--> "libs/indilib"
"libs/ocio-oiio" --u--> "libs/openvdb"
"apps/k3b" --u--> "apps/dvd-rw-tools"
"apps/xmms2" --u--> "apps/fluidsynth"
"apps/audacious" --u--> "apps/fluidsynth"
"apps/calf" --u--> "apps/fluidsynth"
"apps/qsynth" --u--> "apps/fluidsynth"
"apps/museseq" --u--> "apps/fluidsynth"
"apps/octave" --u--> "apps/gnuplot"
"apps/mediainfo-gui" --u--> "apps/mediainfo"
"apps/flacon" --u--> "apps/mediainfo"
"apps/kdenlive" --u--> "apps/mediainfo"
"apps/nut" --u--> "apps/nagios"
"apps/goneovim" --u--> "apps/neovim"
"apps/RcloneBrowser" --u--> "apps/rclone"
"libs/sdl" --u--> "apps/timidity"
"libs/sdl2" --u--> "apps/timidity"
"apps/pidgin" --u--> "libs/farstream"
"apps/dosbox" --u--> "libs/sdl"
"apps/warmux" --u--> "libs/sdl"
"libs/mlt" --u--> "libs/sdl2"
"libs/pygame" --u--> "libs/sdl2"
"apps/hedgewars" --u--> "libs/sdl2"
"apps/neverball" --u--> "libs/sdl2"
"apps/easyeffects" --u--> "apps/calf"
"apps/digikam" --u--> "apps/hugin"
"apps/kdenlive" --u--> "libs/mlt"
"apps/krita" --u--> "libs/mlt"
"apps/deluge" --u--> "libs/pygame"
"apps/audacity" --u--> "libs/suil"
"apps/qtractor" --u--> "libs/suil"
"apps/conky" --u--> "apps/cmus"
"libs/gtkmm" --u--> "apps/graphviz"
"apps/doxygen" --u--> "apps/graphviz"
"apps/lyx" --u--> "apps/graphviz"
"apps/plantuml" --u--> "apps/graphviz"
"apps/seq24" --u--> "libs/gtkmm"
"apps/gimp" --u--> "libs/libmypaint"
"apps/mypaint" --u--> "libs/libmypaint"
"apps/krita" --u--> "libs/libmypaint"
"apps/xsane" --u--> "apps/gimp"
"apps/krita" --u--> "libs/ocio-oiio"
"apps/blender" --u--> "libs/ocio-oiio"
"apps/displaycal-py3" --u--> "libs/wxpython"
"apps/umbrello" --u--> "apps/kdevelop"

@enduml
