{{ define "build" }}

env:
{{ if .Values.labels }}
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
{{ else }}
- JOBS=3
{{ end }}
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"

requires:
{{ range .Values.build_requires }}
- category: {{ .category }}
  name: {{ .name }}
  version: ">=0"
{{ end }}

{{ if .Values.requires_final_images }}
requires_final_images: {{ .Values.requires_final_images }}
{{ end }}

{{ if .Values.unpack }}
unpack: {{ .Values.unpack }}
{{ end }}

prelude:
{{ $packages := include "cr.list_package_with_deps" .Values }}
{{ if $packages }}
{{ range $packages | splitList " " }}
{{ if . }}
{{ $package := . | replace "layerbase-" "layers-" | replace "buildbase-" "layers-" | replace "\"" "" }}
{{ include "cr.copy_package_setup_files" $package }}
{{ end }}
{{ end }}
{{ end }}

{{ include "cr.packages_setup" .Values }}

{{ range include "cr.prereqs" .Values | fromJsonArray }}
{{ if contains "\n" . }}
- |
{{ . | indent 2 }}
{{ else }}
- {{ . }}
{{ end }}
{{ end }}

{{ if eq .Values.category "layerbase" }}
- |
  rm -rf /etc/portage/package.accept_keywords || true; \
  rm -rf /etc/portage/package.license || true; \
  rm -rf /etc/portage/package.unmask || true; \
  rm -rf /etc/portage/package.use || true;
{{ end }}

steps:

{{ if .Values.setup }}
{{ range .Values.setup }}
{{ if . }}
{{ if contains "\n" . }}
- |
{{ . | indent 2 }}
{{ else }}
- {{ . }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}

{{ if eq .Values.category "layerbase" }}
{{ $package := printf "%s-%s" .Values.category .Values.name | replace "layerbase-" "layers-" | replace "buildbase-" "layers-" }}
{{ include "cr.copy_package_setup_files" $package }}
{{ include "cr.package_setup" .Values }}
{{ end }}

{{ if .Values.preemerge }}
{{ range .Values.preemerge }}
{{ $command := include "cr.emerge" . }}
{{ if $command }}
- {{ $command }}
{{ end }}
{{ end }}
{{ end }}

{{ if .Values.labels }}
{{ if ( index .Values.labels "emerge.packages" ) }}
{{ $command := include "cr.emerge" ( index .Values.labels "emerge.packages" ) }}
{{ if $command }}
- {{ $command }}
{{ end }}
{{ end }}
{{ end }}

{{ if .Values.unmerge }}
{{ range .Values.unmerge }}
- emerge -C {{ . }}
{{ end }}
{{ end }}
{{ if .Values.etc_update }}
{{ if .Values.etc_update.mode }}
- etc-update -q --automode {{ .Values.etc_update.mode }}
{{ end }}
{{ end }}

{{ if .Values.completion }}
{{ range .Values.completion }}
{{ if . }}
{{ if contains "\n" . }}
- |
{{ . | indent 2 }}
{{ else }}
- {{ . }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}

# {{ if eq .Values.category "layerbase" }}
# includes:
# - ^/etc/portage/package.accept_keywords/.*
# - ^/etc/portage/package.license/.*
# - ^/etc/portage/package.unmask/.*
# - ^/etc/portage/package.use/.*
# {{ end }}

{{ if ne .Values.category "buildbase" }}
excludes:
- ^/etc/csh.env
- ^/etc/environment.d/10-gentoo-env.conf
- ^/etc/ld.so.conf
- ^/etc/profile.env
- ^/luetbuild
- ^/usr/portage
- ^/usr/portage/distfiles
- ^/usr/share/applications/mimeinfo.cache
- ^/var/cache/edb
- ^/var/cache/distfiles
- ^/var/cache/fontconfig
{{ if ne .Values.category "layerbase" }}
- ^/var/db/pkg
{{ end }}
- ^/var/db/repos
- ^/var/lib/portage
- ^/var/log
# devel split
# - ^/usr/include
# - ^/luetbuild
# - ^/tmp
{{ end }}

# {{ if eq .Values.category "layerbase" }}
# subpackages:
#   - category: "layers"
#     name: "{{ .Values.name }}"
#     version: "{{ .Values.version }}"
#     excludes:
#     - ^/var
#     hidden: false
# {{ end }}

#     includes:
#     - ^/var/db/pkg/.*
#     excludes:
#     - ^/var$
#     - ^/var/db$

{{ if .Values.excludes }}
{{ range .Values.excludes }}
{{ if . }}
- {{ . }}
{{ end }}
{{ end }}
{{ end }}

{{ end }}
