name: Build Set

on:
  workflow_call:
    inputs:
      build-sets:
        type: string
        required: true
        description: 'Stringified JSON object listing target build sets'
      set-id:
        type: string
        required: true
        description: 'Target build set id'
    secrets:
      QUAY_ROBOT_USERNAME:
        required: true
      QUAY_ROBOT_PASSWORD:
        required: true

jobs:
  build:
    if: ${{ inputs.build-sets != '' && inputs.build-sets != '[]' && inputs.build-sets != '[[]]' && fromJson(inputs.build-sets)[inputs.set-id] }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.build-sets)[inputs.set-id] }}
    outputs:
      matrix-sets: ${{ inputs.build-sets }}
    env:
      FINAL_REPO: quay.io/mocaccino/mocaccino-community
      CURRENT_PACKAGE: ${{ matrix.category }}/${{ matrix.name }}@${{ matrix.version }}
      PULL_REPOSITORY: quay.io/mocaccino/desktop
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, x64]
    steps:
    - uses: actions/checkout@v3
    - name: Release space from worker ♻
      if: always()
      run: |
          sudo rm -rf build || true
          sudo rm -rf bin || true
          sudo rm /usr/bin/luet || true
          sudo rm -Rf /etc/luet/ || true
          sudo rm -Rf /var/tmp/luet || true
          sudo rm -Rf /var/luet || true
          sudo docker system prune -f -a --volumes || true
    - name: Release space from worker ♻
      run: |
        echo "Listing top largest packages"
        pkgs=$(dpkg-query -Wf '${Installed-Size}\t${Package}\t${Status}\n' | awk '$NF == "installed"{print $1 "\t" $2}' | sort -nr)
        head -n 30 <<< "${pkgs}"
        echo
        df -h
        echo
        sudo apt-get remove -y '^llvm-.*|^libllvm.*' || true
        sudo apt-get remove --auto-remove android-sdk-platform-tools || true
        sudo apt-get purge --auto-remove android-sdk-platform-tools || true
        sudo rm -rf /usr/local/lib/android
        sudo apt-get remove -y '^dotnet-.*|^aspnetcore-.*' || true
        sudo rm -rf /usr/share/dotnet
        sudo apt-get remove -y '^mono-.*' || true
        sudo apt-get remove -y '^ghc-.*' || true
        sudo apt-get remove -y '.*jdk.*|.*jre.*' || true
        sudo apt-get remove -y 'php.*' || true
        sudo apt-get remove -y hhvm powershell firefox monodoc-manual msbuild || true
        sudo apt-get remove -y '^google-.*' || true
        sudo apt-get remove -y azure-cli || true
        sudo apt-get remove -y '^mongo.*-.*|^postgresql-.*|^mysql-.*|^mssql-.*' || true
        sudo apt-get remove -y '^gfortran-.*' || true
        sudo apt-get autoremove -y
        sudo apt-get clean
        echo
        echo "Listing top largest packages"
        pkgs=$(dpkg-query -Wf '${Installed-Size}\t${Package}\t${Status}\n' | awk '$NF == "installed"{print $1 "\t" $2}' | sort -nr)
        head -n 30 <<< "${pkgs}"
        echo
        sudo rm -rfv build || true
        df -h
    - run: |
        git fetch --prune --unshallow
    - name: Login to Quay Registry
      run: |
        echo ${{ secrets.QUAY_ROBOT_PASSWORD }} | docker login -u ${{ secrets.QUAY_ROBOT_USERNAME }} --password-stdin quay.io

    - name: Install deps 🔧
      run: |
        curl https://luet.io/install.sh | sudo sh
    - name: Install Go
      uses: actions/setup-go@v3
      with:
          go-version: '^1.16'
    - name: Install CI plugins
      run: |
            sudo cp -rfv .github/plugins/* /usr/bin/
    - name: Build packages 🔧
      run: |
        export LUET_NOLOCK=true
        # sudo -E luet install -y repository/mocaccino-desktop
        sudo -E luet install -y repository/mocaccino-desktop-stable
        sudo -E luet install -y repository/mocaccino-os-commons
        sudo -E luet install -y repository/mocaccino-extra-stable
        export PATH=$PATH:/usr/local/go/bin
        mkdir build || true
        pushd ./.github
        go build -o build
        popd
        sudo -E ./.github/build
        ls -liah $PWD/build
        sudo chmod -R 777 $PWD/build
    - uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: ${{ matrix.category }}-${{ matrix.name }}-${{ matrix.version }}.zip
        path: |
          build/
