name: Check packages for upgrade availability
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: [self-hosted, x64]
    env:
      ROOT_PATH: ..
    steps:
      - uses: actions/checkout@v3
      - run: |
          git fetch --prune --unshallow
      - name: Install deps 🔧
        run: |
          curl https://luet.io/install.sh | sudo sh
          export LUET_NOLOCK=true
          sudo -E luet install -y repository/mocaccino-extra
          sudo -E luet install -y utils/jq
          sudo -E luet install -y utils/yq
      - name: Check packages for upgrade availability
        run: |
          ./scripts/up.sh
          set -x
          ls -liahR
          ls -liahR $PWD
          ls -liahR ..
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: packages_reports.zip
          path: |
            reports/
