name: Check packages for upgrade availability
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: [self-hosted, x64]
    env:
      ROOT_PATH: ./community-repository
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          curl https://luet.io/install.sh | sudo sh
          sudo luet install -y repository/mocaccino-extra
          sudo luet install -y utils/jq
          sudo luet install -y utils/yq
      - name: Check packages for upgrade availability
        run: |
          ./scripts/up.sh
