name: Check packages for upgrade availability
on:
  workflow_dispatch:
jobs:
  run:
    env:
      ROOT_PATH="./community-repository"
    runs-on: [self-hosted, x64]
    steps:
      - uses: actions/checkout@v3
      - name: Check packages for upgrade availability
        run: |
                ./scripts/run.sh up.sh
